# name: Rust

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# env:
#   CARGO_TERM_COLOR: always

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3

#     # Setup Rust toolchain
#     - name: Install Rust toolchain
#       uses: actions-rs/toolchain@v1
#       with:
#         profile: minimal
#         toolchain: stable
#         override: true

#     # Install cargo-tarpaulin for code coverage
#     - name: Install cargo-tarpaulin
#       uses: cargo install cargo-tarpaulin

#     # Install cargo-clippy for linting
#     - name: Install clippy
#       run: rustup component add clippy

#     # cargo fmt does not need to be installed as it comes with the rustup toolchain

#     # Install cargo-audit for security audit
#     - name: Install cargo-audit
#       run: cargo install cargo-audit

#     # Build
#     - name: Build
#       run: cargo build --verbose

#     # Run tests
#     - name: Run tests
#       run: cargo test --verbose

#     # Code Coverage
#     - name: Code Coverage
#       run: cargo tarpaulin --ignore-tests

#     # Code Linter
#     - name: Code Linter
#       run: cargo clippy -- -D warnings

#     # Code formatter
#     - name: Code formatter
#       run: cargo fmt -- --check

#     # Security audit
#     - name: Security audit
#       run: cargo audit


name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # # Install cargo-clippy for linting
    # - name: Install clippy
    #   run: rustup component add clippy

    # # cargo fmt does not need to be installed as it comes with the rustup toolchain

    # # Install cargo-audit for security audit
    # - name: Install cargo-audit
    #   run: cargo install cargo-audit

    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    # - name: Code Linter
    #   run: cargo clippy --all-targets --all-features    
    - name: Code formatter
      run: cargo fmt -- --check
    # - name: Securiy audit
    #   run: cargo audit
